export const COMMON_DATA_PACKAGES = [
  { id: 'pandas', name: 'pandas', description: '数据分析核心库' },
  { id: 'numpy', name: 'numpy', description: '数值计算' },
  { id: 'matplotlib', name: 'matplotlib', description: '数据可视化' },
  { id: 'seaborn', name: 'seaborn', description: '统计制图' },
  { id: 'scikit-learn', name: 'scikit-learn', description: '机器学习' },
  { id: 'scipy', name: 'scipy', description: '科学计算' },
  { id: 'openpyxl', name: 'openpyxl', description: 'Excel 读写 (xlsx)' },
  { id: 'xlrd', name: 'xlrd', description: 'Excel 读取 (xls)' },
  { id: 'xlsxwriter', name: 'xlsxwriter', description: 'Excel 写入' },
  { id: 'requests', name: 'requests', description: 'HTTP 请求' },
  { id: 'sqlalchemy', name: 'sqlalchemy', description: '数据库 ORM' },
  { id: 'beautifulsoup4', name: 'beautifulsoup4', description: '网页解析' },
  { id: 'jupyterlab', name: 'jupyterlab', description: 'Jupyter 交互环境' },
  { id: 'notebook', name: 'notebook', description: '经典 Notebook' },
  { id: 'ipython', name: 'ipython', description: '增强版交互式 Python' },
  { id: 'plotly', name: 'plotly', description: '交互式可视化' },
  { id: 'tqdm', name: 'tqdm', description: '进度条工具' },
  { id: 'pyinstaller', name: 'pyinstaller', description: '打包成 exe' },
];
